name: Build Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-macos:
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install dependencies
        run: brew install automake libtool libsndfile fftw

      - name: Make and test
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          make
          ctest -C Release

      - name: Prepare output
        run: |
          pushd include
          zip -r ../include.zip .
          popd
          mv build/src/libsamplerate.a ./libsamplerate-macos12.a
          mv COPYING LICENSE

      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: build-output-macos12
          path: |
            include.zip
            libsamplerate-macos12.a
            LICENSE

  build-macos-arm64:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install dependencies
        run: brew install automake libtool libsndfile fftw

      - name: Make and test
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          make
          ctest -C Release

      - name: Prepare output
        run: mv build/src/libsamplerate.a ./libsamplerate-macos-arm64.a

      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: build-output-macos-arm64
          path: libsamplerate-macos-arm64.a

  build-linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Get RPi toolchain
        run: |
          wget https://github.com/sfjohnson/rpi-toolchain/releases/download/v0.1.8/aarch64-rpi4-linux-gnu.tar.xz
          tar xf aarch64-rpi4-linux-gnu.tar.xz -C ~

      - name: Make RPi
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF -DLIBSAMPLERATE_EXAMPLES=OFF ..
          make
          mv src/libsamplerate.a ../libsamplerate-rpi-arm64.a
        env:
          CC: ${{ env.HOME }}/aarch64-rpi4-linux-gnu/bin/aarch64-rpi4-linux-gnu-gcc

      - name: Configure and make linux-x64
        run: |
          rm -rf build
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          make
          ctest -C Release
          mv src/libsamplerate.a ../libsamplerate-linux-x64.a

      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: build-output-linux
          path: |
            libsamplerate-rpi-arm64.a
            libsamplerate-linux-x64.a

  create-release:
    runs-on: ubuntu-22.04
    needs: [build-macos, build-linux, build-macos-arm64]
    steps:
      - name: Get build output macos12
        uses: actions/download-artifact@v4
        with:
          name: build-output-macos12

      - name: Get build output linux
        uses: actions/download-artifact@v4
        with:
          name: build-output-linux

      - name: Get build output macos-arm64
        uses: actions/download-artifact@v4
        with:
          name: build-output-macos-arm64

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            include.zip
            libsamplerate-macos12.a
            libsamplerate-rpi-arm64.a
            libsamplerate-macos-arm64.a
            libsamplerate-linux-x64.a
            LICENSE
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
